services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: language_learning_app
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  language-learning-app:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - app_uploads:/app/uploads
      - ./sentencewise_full.jsonl:/app/sentencewise_full.jsonl:ro
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DB_USER=app_user
      - DB_PASSWORD=app_password
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=language_learning_app
      - DATABASE_URL=postgresql://app_user:app_password@postgres:5432/language_learning_app
      - SECRET_KEY=your-production-secret-key-here
      - JWT_SECRET_KEY=your-production-jwt-secret-here
      - UPLOAD_FOLDER=/app/uploads
      - NEURAL_NETWORK_MODEL_PATH=Zlovoblachko/REAlEC_2step_model_testing
      - GED_MODEL_PATH=Zlovoblachko/11tag-electra-grammar-stage2
    depends_on:
      - postgres
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

volumes:
  postgres_data:
  app_uploads: