"""replace exercise system with practice sessions

Revision ID: 12a40c90d01c
Revises: f42d3069a5b8
Create Date: 2026-08-24 04:24:32.981614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12a40c90d01c'
down_revision = 'f42d3069a5b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('sentence_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_step', sa.String(length=20), nullable=False),
    sa.Column('original_sentence', sa.Text(), nullable=False),
    sa.Column('target_corrected', sa.Text(), nullable=False),
    sa.Column('round_target', sa.Text(), nullable=True),
    sa.Column('queue', sa.Text(), nullable=True),
    sa.Column('current_item', sa.Text(), nullable=True),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('sentences_completed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('time_spent_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_practice_sessions_student_id_users')),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('fk_practice_sessions_submission_id_submissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_sessions'))
    )
    op.create_table('practice_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('sentence_index', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('practice_session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['practice_session_id'], ['practice_sessions.id'], name=op.f('fk_practice_assignments_practice_session_id_practice_sessions')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_practice_assignments_student_id_users')),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('fk_practice_assignments_submission_id_submissions')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_practice_assignments_teacher_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_assignments'))
    )
    # submissions.exercise_id's FK must be dropped before the `exercises` table it points at -
    # autogenerate ordered these the other way round, which fails against a database that
    # actually has the constraint (DependentObjectsStillExist). This block moved up. The
    # constraint name follows this app's naming convention (models/__init__.py's `fk_%(table)s
    # _%(column)s_%(referred_table)s`, in place since the very first commit) - NOT Postgres's
    # own default `submissions_exercise_id_fkey`, since every real deployment's schema (via
    # db.create_all(), which has always used this same naming MetaData) already has it under
    # the convention name.
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempt_number', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('parent_submission_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_submissions_exercise_id_exercises'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_submissions_parent_submission_id_submissions'), 'submissions', ['parent_submission_id'], ['id'])
        batch_op.drop_column('exercise_id')

    op.drop_table('exercise_attempts')
    op.drop_table('sentences')
    op.drop_table('exercises')
    # Note: autogenerate also proposed renaming users_email_key/users_username_key/
    # invitations_code_key to their uq_-prefixed convention names, comparing against a
    # hand-built disposable test database that (unlike every real deployment) didn't apply the
    # app's naming convention when created. Every real deployment's unique constraints already
    # have the convention names from day one, so there's nothing to rename here.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Reordered from the raw autogenerate output: `exercises` must exist again before
    # submissions.exercise_id's FK is recreated against it (the generated order had it the
    # other way round, which fails - see the matching note in upgrade()). The spurious
    # users/invitations unique-constraint rename (see upgrade()'s note) is dropped too.
    op.create_table('exercises',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_submission_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('instructions', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sentences', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'draft'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('exercises_creator_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('exercises_pkey'))
    )
    op.create_table('sentences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('error_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sentences_pkey'))
    )
    op.create_table('exercise_attempts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('responses', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('analysis_result', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('time_spent_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('exercise_attempts_exercise_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('exercise_attempts_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('exercise_attempts_pkey'))
    )

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_submissions_parent_submission_id_submissions'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_submissions_exercise_id_exercises'), 'exercises', ['exercise_id'], ['id'])
        batch_op.drop_column('score')
        batch_op.drop_column('parent_submission_id')
        batch_op.drop_column('attempt_number')

    op.drop_table('practice_assignments')
    op.drop_table('practice_sessions')
    # ### end Alembic commands ###
