"""one reusable invitation code per teacher

Revision ID: 352b04c9e747
Revises: 2fee6ca8a184
Create Date: 2026-09-24 23:25:40.236767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '352b04c9e747'
down_revision = '2fee6ca8a184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_invitations_code'), type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invitation_code', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_users_invitation_code'), ['invitation_code'])

    # Adopt each teacher's most recent still-unused single-use code as their permanent one, so
    # any code already handed out to students keeps working after the switch. Teachers with no
    # unused code left are simply issued one the next time they open the dialog.
    op.execute("""
        UPDATE users u
        SET invitation_code = sub.code
        FROM (
            SELECT DISTINCT ON (teacher_id) teacher_id, code
            FROM invitations
            WHERE is_used = false
            ORDER BY teacher_id, created_at DESC, id DESC
        ) sub
        WHERE u.id = sub.teacher_id
          AND u.role = 'teacher'
          AND u.invitation_code IS NULL
    """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_invitation_code'), type_='unique')
        batch_op.drop_column('invitation_code')

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_invitations_code'), ['code'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
