"""add error logs, activity sessions, time tracking columns

Revision ID: 9d93b537b5dc
Revises: 0a1b2c3d4e5f
Create Date: 2026-08-23 02:35:08.876218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d93b537b5dc'
down_revision = '0a1b2c3d4e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('active_seconds', sa.Float(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_activity_sessions_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_sessions'))
    )
    op.create_table('error_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('sentence_index', sa.Integer(), nullable=True),
    sa.Column('errant_type', sa.String(length=40), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('corrected_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_error_logs_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_error_logs'))
    )
    with op.batch_alter_table('exercise_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_spent_seconds', sa.Float(), nullable=True))

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_spent_seconds', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('time_spent_seconds')

    with op.batch_alter_table('exercise_attempts', schema=None) as batch_op:
        batch_op.drop_column('time_spent_seconds')

    op.drop_table('error_logs')
    op.drop_table('activity_sessions')
    # ### end Alembic commands ###
