"""add invitation student_id link

Revision ID: f42d3069a5b8
Revises: 9d93b537b5dc
Create Date: 2026-08-23 04:52:04.401975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42d3069a5b8'
down_revision = '9d93b537b5dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_invitations_student_id_users'), 'users', ['student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_invitations_student_id_users'), type_='foreignkey')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
