// Auth types
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const LOGOUT = 'LOGOUT';
export const AUTH_CHECK = 'AUTH_CHECK';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';

// Task types
export const FETCH_TASKS_REQUEST = 'FETCH_TASKS_REQUEST';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE';
export const FETCH_TASK_REQUEST = 'FETCH_TASK_REQUEST';
export const FETCH_TASK_SUCCESS = 'FETCH_TASK_SUCCESS';
export const FETCH_TASK_FAILURE = 'FETCH_TASK_FAILURE';
export const CREATE_TASK_REQUEST = 'CREATE_TASK_REQUEST';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_FAILURE = 'CREATE_TASK_FAILURE';
export const ASSIGN_TASK_REQUEST = 'ASSIGN_TASK_REQUEST';
export const ASSIGN_TASK_SUCCESS = 'ASSIGN_TASK_SUCCESS';
export const ASSIGN_TASK_FAILURE = 'ASSIGN_TASK_FAILURE';

// Submission types
export const FETCH_SUBMISSIONS_REQUEST = 'FETCH_SUBMISSIONS_REQUEST';
export const FETCH_SUBMISSIONS_SUCCESS = 'FETCH_SUBMISSIONS_SUCCESS';
export const FETCH_SUBMISSIONS_FAILURE = 'FETCH_SUBMISSIONS_FAILURE';
export const FETCH_SUBMISSION_REQUEST = 'FETCH_SUBMISSION_REQUEST';
export const FETCH_SUBMISSION_SUCCESS = 'FETCH_SUBMISSION_SUCCESS';
export const FETCH_SUBMISSION_FAILURE = 'FETCH_SUBMISSION_FAILURE';
export const CREATE_SUBMISSION_REQUEST = 'CREATE_SUBMISSION_REQUEST';
export const CREATE_SUBMISSION_SUCCESS = 'CREATE_SUBMISSION_SUCCESS';
export const CREATE_SUBMISSION_FAILURE = 'CREATE_SUBMISSION_FAILURE';
export const REVIEW_SUBMISSION_REQUEST = 'REVIEW_SUBMISSION_REQUEST';
export const REVIEW_SUBMISSION_SUCCESS = 'REVIEW_SUBMISSION_SUCCESS';
export const REVIEW_SUBMISSION_FAILURE = 'REVIEW_SUBMISSION_FAILURE';

// Exercise types
export const FETCH_EXERCISES_REQUEST = 'FETCH_EXERCISES_REQUEST';
export const FETCH_EXERCISES_SUCCESS = 'FETCH_EXERCISES_SUCCESS';
export const FETCH_EXERCISES_FAILURE = 'FETCH_EXERCISES_FAILURE';
export const FETCH_EXERCISE_REQUEST = 'FETCH_EXERCISE_REQUEST';
export const FETCH_EXERCISE_SUCCESS = 'FETCH_EXERCISE_SUCCESS';
export const FETCH_EXERCISE_FAILURE = 'FETCH_EXERCISE_FAILURE';
export const CREATE_EXERCISE_REQUEST = 'CREATE_EXERCISE_REQUEST';
export const CREATE_EXERCISE_SUCCESS = 'CREATE_EXERCISE_SUCCESS';
export const CREATE_EXERCISE_FAILURE = 'CREATE_EXERCISE_FAILURE';
export const SUBMIT_EXERCISE_ATTEMPT_REQUEST = 'SUBMIT_EXERCISE_ATTEMPT_REQUEST';
export const SUBMIT_EXERCISE_ATTEMPT_SUCCESS = 'SUBMIT_EXERCISE_ATTEMPT_SUCCESS';
export const SUBMIT_EXERCISE_ATTEMPT_FAILURE = 'SUBMIT_EXERCISE_ATTEMPT_FAILURE';
export const FETCH_EXERCISE_ATTEMPTS_REQUEST = 'FETCH_EXERCISE_ATTEMPTS_REQUEST';
export const FETCH_EXERCISE_ATTEMPTS_SUCCESS = 'FETCH_EXERCISE_ATTEMPTS_SUCCESS';
export const FETCH_EXERCISE_ATTEMPTS_FAILURE = 'FETCH_EXERCISE_ATTEMPTS_FAILURE';

// UI types
export const SET_ALERT = 'SET_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';